version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Installing dependencies..."
      - yum install -y maven
  pre_build:
    commands:
      - echo "Compiling the project..."
      - mvn clean compile

  build:
    commands:
      - echo start build.

      # Spring Bootプロジェクトのビルド（jarの作成）
      - mvn package
      - ls -l target

      - echo finish build.

  post_build:
    commands:
      - echo start post build.

      # S3にアップロードするファイルを所定のディレクトリにコピー
      - mkdir artifacts
      - cp target/passaydemo-0.0.1-SNAPSHOT.jar artifacts
      - cp appspec.yml artifacts

      - echo finish post build.

artifacts:
  # S3にアップロードするファイルを指定
  files:
    - passaydemo-0.0.1-SNAPSHOT.jar
    - appspec.yml
  # ベースディレクトリ
  base-directory: artifacts